<?php

/* Default options */
const DEFAULT_CONTROLLER = "Reserva";
const DEFAULT_ACTION = "list";

const CONTROLLERS_FOLDER="controller";

const MODELS_FOLDER = "model";
const REPOSITORIES_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."repository";
const ENTITIES_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."entity";
const SERVICES_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."service";


const INCLUDES_FOLDER="includes";
const TRAITS_FOLDER=MODELS_FOLDER.DIRECTORY_SEPARATOR."traits";


?>